name: Add badge with total amount of problems solved

on:
  push: 
    branches:
      - test-ci

env:
  SOLVED: unknown
  ARTIFACT_NAME: total-solved

jobs:
  count-solved:
    name: Count solved problems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: test-ci

      - name: Calculate amount of problems solved
        run: echo "SOLVED=$(find . -type f | grep -E '*\.(cpp|py)' | wc -l)" >> $GITHUB_ENV
  
  create-total-solved-badge:
    name: Create total solved badge
    runs-on: ubuntu-latest
    needs: count-solved
    env:
      BADGE_PATH: ./total-solved.svg 
    steps:
      - name: Generate badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Problems solved
          status: ${{ env.SOLVED }}
          color: red
          scale: 1
          style: flat
          path: ${{ env.BADGE_PATH }}

      - name: Upload badge as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BADGE_PATH }}
  
  commit-badge:
    name: Commit badge to separate branch
    runs-on: ubuntu-latest
    needs: create-total-solved-badge
    env:
      BADGE_BRANCH: badges
    steps:
      - name: Ensure branch with badges exists
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.BADGE_BRANCH }}
      
      - name: Checkout to branch with badges
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BADGE_BRANCH }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Commit badge
        continue-on-error: false
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -m "Update badges"

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BADGE_BRANCH }}
