name: Add badge with total amount of problems solved

on:
  push: 
    branches:
      - test-ci

jobs:
  add-badge:
    name: Add badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: test-ci

      - name: Calculate amount of problems solved
        run: echo "SOLVED=$(find . -type f | grep -E '*\.(cpp|py)' | wc -l)" >> $GITHUB_ENV

      - name: Create directory for badges
        run: mkdir -p .github/badges

      - name: Generate badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Problems solved
          status: ${{ env.SOLVED }}
          color: red
          scale: 1
          style: flat
          path: .github/badges/total-solved.svg

      - name: Commit badge
        continue-on-error: false
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/total-solved.svg
          git commit -m "Add/Update badge"

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges
