name: Add badge with total amount of problems solved

on:
  push: 
    branches:
      - test-ci

env:
  SOLVED: unknown

jobs:
  count-solved:
    name: Count solved problems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: test-ci

      - name: Calculate amount of problems solved
        run: echo "SOLVED=$(find . -type f | grep -E '*\.(cpp|py)' | wc -l)" >> $GITHUB_ENV
  
  update-badge:
    name: Update badge
    runs-on: ubuntu-latest
    needs: count-solved
    steps:
      - name: Generate badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Problems solved
          status: ${{ env.SOLVED }}
          color: red
          scale: 1
          style: flat
          path: ./total-solved.svg

      - name: Commit badge
        continue-on-error: false
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./total-solved.svg
          git commit -m "Update badge"

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges
